version: '3'
services:
  streamlit:
    build:
      context: .
      dockerfile: streamlit/dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - ./data:/app/data  # Mount the data folder for Streamlit

